apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/crossplane/crossplane/v2.1.3/cluster/crds/pkg.crossplane.io_deploymentruntimeconfigs.yaml
  - https://raw.githubusercontent.com/crossplane/crossplane/v2.1.3/cluster/crds/pkg.crossplane.io_providers.yaml
